---
- hosts: ws
  become: true
  tasks:
    - name: Update all packages
      package:  
        name: '*'
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present
        

    - name: Start Daemon
      service:
        name: httpd
        state: started
        enabled: true


    # - name: Delete file if exits
    #   file:
    #     path: /var/www/html/index.html
    #     state: absent
    #   ignore_errors: true

    - name: Create a file
      file:
        dest: /var/www/html/index.html
        state: touch


    - name: Add content to our file
      lineinfile:
        path: /var/www/html/index.html
        line: <h1> This apache webserver was built using ansible and we are making progres</h1>
      notify: Restart Daemon  



        
  handlers:
    - name: Restart Daemon
      service:
        name: httpd
        state: restarted
        
